name: test123
services:

  client-facing:
    build:
      context: ./clientfacing
    container_name: client-facing
    depends_on:
      - client-facing-db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_PASSWORD=client_db_password
      - SPRING_DATASOURCE_USERNAME=client_db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://client-facing-db:5432/client_db
      - SPRING_DATA_JDBC_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

    ports:
      - "8080:8080"

  employee-facing:
    build:
      context: ./employeefacing
    container_name: employee-facing
    depends_on:
      - employee-facing-db
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_PASSWORD=employee_db_password
      - SPRING_DATASOURCE_USERNAME=employee_db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://employee-facing-db:5433/employee_db
      - SPRING_DATA_JDBC_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

    ports:
      - "8081:8081"

  client-facing-db:
    image: postgres
    container_name: client-facing-db
    environment:
      - POSTGRES_USER=client_db
      - POSTGRES_PASSWORD=client_db_password
      - POSTGRES_DB=client_db
    ports:
      - "5432:5432"

  employee-facing-db:
    image: postgres
    container_name: employee-facing-db
    environment:
      - POSTGRES_USER=employee_db
      - POSTGRES_PASSWORD=employee_db_password
      - POSTGRES_DB=employee_db
    ports:
      - "5432:5433"